# build an excutable program named "structure_factor"
CC		= gcc
all: structure_factor.cpp
	icc -g -Wall -o structure_factor structure_factor.cpp -lm
	icc -g -Wall -o structure_factor_refined structure_factor_refined.cpp -lm
clean:
	rm structure_factor
